export type CategoryKind = "fixed" | "variable";

export const DEFAULT_CATEGORIES: Array<{ name: string; kind: CategoryKind }> = [
  { name: "Aluguel / Hipoteca", kind: "fixed" },
  { name: "Condomínio", kind: "fixed" },
  { name: "Energia Elétrica", kind: "fixed" },
  { name: "Água e Saneamento", kind: "fixed" },
  { name: "Gás", kind: "fixed" },
  { name: "Internet Residencial", kind: "fixed" },
  { name: "Plano de Celular", kind: "fixed" },
  { name: "Assinaturas (Streaming/Software)", kind: "fixed" },
  { name: "Seguro Saúde / Plano de Saúde", kind: "fixed" },
  { name: "Seguro Residencial", kind: "fixed" },
  { name: "Seguro Auto", kind: "fixed" },
  { name: "Licenciamento Auto", kind: "fixed" },
  { name: "Renovação Habilitação", kind: "fixed" },
  { name: "Parcela de Veículo / Financiamento", kind: "fixed" },
  { name: "Mensalidade Escolar / Faculdade", kind: "fixed" },
  { name: "Cursos e Idiomas", kind: "fixed" },
  { name: "Academia / Esportes", kind: "fixed" },
  { name: "Terapia / Psicólogo", kind: "fixed" },
  { name: "Dízimo", kind: "fixed" },
  { name: "Mercado (Alimentação e Higiene)", kind: "variable" },
  { name: "Restaurantes e Delivery", kind: "variable" },
  { name: "Padaria e Lanches", kind: "variable" },
  { name: "Feira / Hortifruti", kind: "variable" },
  { name: "Combustível", kind: "variable" },
  { name: "Transporte por App", kind: "variable" },
  { name: "Transporte Público", kind: "variable" },
  { name: "Estacionamento e Pedágio", kind: "variable" },
  { name: "Manutenção de Veículo", kind: "variable" },
  { name: "Farmácia e Medicamentos", kind: "variable" },
  { name: "Consultas e Exames", kind: "variable" },
  { name: "Barbearia / Salão / Estética", kind: "variable" },
  { name: "Vestuário (Roupas e Calçados)", kind: "variable" },
  { name: "Presentes e Doações", kind: "variable" },
  { name: "Cinema / Shows / Eventos", kind: "variable" },
  { name: "Hobbies e Games", kind: "variable" },
  { name: "Viagens e Passeios", kind: "variable" },
  { name: "Manutenção Residencial (Reparos)", kind: "variable" },
  { name: "Imprevistos / Emergências", kind: "variable" },
];

export const CATEGORY_KIND_LABELS: Record<CategoryKind, string> = {
  fixed: "Custo fixo",
  variable: "Variável",
};
